# Docker Compose configuration for DevSecOps Pipeline

services:
  # Основное приложение Defect Dojo
  defectdojo:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=dev-secret-key-change-in-production
      - DATABASE_URL=postgresql://defectdojo:defectdojo@db:5432/defectdojo
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - defectdojo-network
    restart: unless-stopped

  # База данных PostgreSQL
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=defectdojo
      - POSTGRES_USER=defectdojo
      - POSTGRES_PASSWORD=defectdojo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - defectdojo-network
    restart: unless-stopped

  # Redis для кеширования
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass defectdojo
    volumes:
      - redis_data:/data
    networks:
      - defectdojo-network
    restart: unless-stopped

  # SonarQube для анализа кода
  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - defectdojo-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  sonarqube_data:
    driver: local
  sonarqube_extensions:
    driver: local
  sonarqube_logs:
    driver: local

networks:
  defectdojo-network:
    driver: bridge 